# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/osom/ingot/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ingot)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,ef75f1cca0fd64e6fe8f7f87e44bf35790fffdfd)
$(call add-radio-file-sha1-checked,radio/modem.img,e77e8a9b4a5c8b4a9d14649891b7d99e0e546eee)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,bb4f1a33e217bdfb281cce3c4b80629cf7bf0fc4)
$(call add-radio-file-sha1-checked,radio/abl.img,381f24bfe1c759e73ae1e0dcf238cdf0a1ec0de7)
$(call add-radio-file-sha1-checked,radio/aop.img,917bfce8ab3a2ac644c8006c1c83865db8f8a170)
$(call add-radio-file-sha1-checked,radio/aop_config.img,90279f1dc8de37d69edd637ee1ff820e01563707)
$(call add-radio-file-sha1-checked,radio/cpucp.img,ea75b3fa336a161b4d1305d76da4481747cff5a7)
$(call add-radio-file-sha1-checked,radio/devcfg.img,4233a85dd1f326eb917075faca2fd6c6a4364b42)
$(call add-radio-file-sha1-checked,radio/dsp.img,a932ba870217cc9d3237a103f70393ea28f0a7ef)
$(call add-radio-file-sha1-checked,radio/featenabler.img,b1a85f0868dc83962fb8fdc6669c24975fefec23)
$(call add-radio-file-sha1-checked,radio/hyp.img,fbc337748e6f4c5840439601358dd407bb2f5af1)
$(call add-radio-file-sha1-checked,radio/imagefv.img,0d3461dceed860d38423dc8e2ed4a80c2ff5952f)
$(call add-radio-file-sha1-checked,radio/keymaster.img,e7186e56311587d204448da39a6b901da912e2e5)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,9dc3a32366280665f4e321a1a81e9bcc3bf18428)
$(call add-radio-file-sha1-checked,radio/multiimgqti.img,b608bd84018157be14b6b8672c4c30c0b928c644)
$(call add-radio-file-sha1-checked,radio/qupfw.img,b436809adb324ab1bdc39f8493dde785ae7df5db)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,c7d711a72874c67b93a88a5f17f9479c7af86d17)
$(call add-radio-file-sha1-checked,radio/tz.img,4fae185e2e73b33d97350947be0a3ad93502f1d1)
$(call add-radio-file-sha1-checked,radio/uefi.img,52cfbd52fe4fb3c3e4b3887eecc5470e084a0a12)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,83e46e2cde094b4cc95773b8aa0af7ba6847bf3d)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,37c9bc9a2008528b31cb9cc615d433be903ed087)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,8064b551b69a020dc5d1b8acf2be7350b740136e)
$(call add-radio-file-sha1-checked,radio/xbl.img,c067eabcd103773ad1f467c4429c4bc721ed8d56)

endif
