# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/osom/ingot/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    bluetooth \
    modem \
    xbl_ramdump \
    abl \
    aop \
    aop_config \
    cpucp \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    multiimgoem \
    multiimgqti \
    qupfw \
    qweslicstore \
    shrm \
    tz \
    uefi \
    uefisecapp \
    vm-bootsys \
    xbl_config \
    xbl
